ARRSIZE=$1
MAXARRSIZE=$2
OUTPUTFILE=$3
ARRSIZEINTERVAL=$4

kill -10 $PPID
while [ $ARRSIZE -lt $MAXARRSIZE ]
do
	kill -10 $PID
	echo $(date '+%H:%M:%S') = ARRAY SIZE: $ARRSIZE >> $OUTPUTFILE 
	./bad_program $ARRSIZE $ARRSIZE $ARRSIZE $ARRSIZE 
	ARRSIZE=$(($ARRSIZE + $ARRSIZEINTERVAL))
done
