OUTPUTDIR=$1
LOGINTERVAL=$2
ARRSIZE=$3
ARRSIZEINTERVAL=$4

echo $$ > ./PID.txt

function SIGUSR1_HANDLE(){
	echo $ARRSIZE\n >> $OUTPUTDIR/iostatData.txt
	ARRSIZE=$(($ARRSIZE + $ARRSIZEINTERVAL))
}

trap SIGUSR1_HANDLE SIGUSR1

vmstat -nt $TIMEINTERVAL | tail -n 1 >> $OUTPUTDIR/vmstatData.txt 
